---
language: python
python:
  - "3.6"
cache: pip
services:
  - docker
env:
  - TOX_ENV=py3-ansible27-rabbitmq36
  - TOX_ENV=py3-ansible27-rabbitmq37
  - TOX_ENV=py3-ansible28-rabbitmq36
  - TOX_ENV=py3-ansible28-rabbitmq37
  - TOX_ENV=py3-ansible29-rabbitmq36
  - TOX_ENV=py3-ansible29-rabbitmq37
install:
  - pip install tox
script: tox -e "${TOX_ENV}"

stages:
  - name: test
  - name: mkrelease
    if: |
      branch = master \
      AND type != pull_request

jobs:
  fast_finish: true
  include:
    - stage: mkrelease
      install:
        - pip install ansible
        - wget --quiet -O /tmp/mkrelease.sh https://raw.githubusercontent.com/rockandska/scripts/${MKRELEASE_REF:-master}/CI/mkrelease.sh
        - chmod +x /tmp/mkrelease.sh
        - wget --quiet -O /tmp/pubrelease.sh https://raw.githubusercontent.com/rockandska/scripts/${PUBRELEASE_REF:-master}/CI/pubrelease.sh
        - chmod +x /tmp/pubrelease.sh
      script:
        - export TRAVIS_TAG=$(/tmp/mkrelease.sh)
      deploy:
        provider: script
        script: /tmp/pubrelease.sh ansible-galaxy
        skip_cleanup: true
        on:
          tags: true
