---
- hosts: rabbitmq-master
  remote_user: molecule
  become: true
  any_errors_fatal: true
  pre_tasks:
    - import_tasks: pre_tasks.yml
  roles:
    - role: ansible-role-erlang
      vars:
        erlang_series: "{{ lookup('ENV','ERLANG_SERIES') }}"
    - role: ansible-role-rabbitmq
      vars:
        rabbitmq_series: "{{ lookup('ENV','RABBITMQ_SERIES') }}"

- hosts: rabbitmq-slave
  remote_user: molecule
  become: true
  any_errors_fatal: true
  pre_tasks:
    - import_tasks: pre_tasks.yml
  roles:
    - role: ansible-role-erlang
      vars:
        erlang_series: "{{ lookup('ENV','ERLANG_SERIES') }}"
    - role: ansible-role-rabbitmq
      vars:
        rabbitmq_series: "{{ lookup('ENV','RABBITMQ_SERIES') }}"
